CREATE DATABASE `COOKBOOK` /*!40100 DEFAULT CHARACTER SET utf8 */;

CREATE TABLE `COOKBOOK`.`USER` (
  `USER_ID` INT NOT NULL,
  `USER_NAME` VARCHAR(45) NOT NULL,
  `EMAIL_ID` VARCHAR(45) NOT NULL,
  `CREATED_AT` TIMESTAMP NULL,
  `UPDATED_AT` TIMESTAMP NULL,
  PRIMARY KEY (`USER_ID`),
  UNIQUE INDEX `EMAIL_ID_UNIQUE` (`EMAIL_ID` ASC));

  CREATE TABLE `COOKBOOK`.`DISH` (
  `DISH_ID` INT NOT NULL,
  `NAME` VARCHAR(45) NULL,
  `CREATED_AT` TIMESTAMP NULL,
  `UPDATED_AT` TIMESTAMP NULL,
  `DESCRIPTION` VARCHAR(225) NULL,
  `CATEGORY` VARCHAR(45) NULL,
  PRIMARY KEY (`DISH_ID`));

  CREATE TABLE `COOKBOOK`.`INGREDIENTS` (
  `INGREDIENT_ID` INT NOT NULL,
  `NAME` VARCHAR(45) NULL,
  `COMMON_NAME` VARCHAR(45) NULL,
  `CREATED_AT` TIMESTAMP NULL,
  `UPDATED_AT` TIMESTAMP NULL,
  PRIMARY KEY (`INGREDIENT_ID`));

  CREATE TABLE `COOKBOOK`.`DISH_INGREDIENT` (
  `DISH_INGREDIENT_ID` INT NOT NULL,
  `DISH_ID` INT NULL,
  `INGREDIENT_ID` INT NULL,
  `UNIT` VARCHAR(45) NULL,
  PRIMARY KEY (`DISH_INGREDIENT_ID`),
  INDEX `DISH_ID_idx` (`DISH_ID` ASC),
  INDEX `FK_INGREDIENT_ID_idx` (`INGREDIENT_ID` ASC),
  CONSTRAINT `FK_DISH_ID`
    FOREIGN KEY (`DISH_ID`)
    REFERENCES `COOKBOOK`.`DISH` (`DISH_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_INGREDIENT_ID`
    FOREIGN KEY (`INGREDIENT_ID`)
    REFERENCES `COOKBOOK`.`INGREDIENTS` (`INGREDIENT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE TABLE `COOKBOOK`.`USER_DISH` (
  `USER_DISH_ID` INT NOT NULL,
  `DISH_ID` INT NULL,
  `USER_ID` INT NULL,
  PRIMARY KEY (`USER_DISH_ID`),
  INDEX `FK1_DISH_ID_idx` (`DISH_ID` ASC),
  INDEX `FK_USER_ID_idx` (`USER_ID` ASC),
  CONSTRAINT `FK1_DISH_ID`
    FOREIGN KEY (`DISH_ID`)
    REFERENCES `COOKBOOK`.`DISH` (`DISH_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_USER_ID`
    FOREIGN KEY (`USER_ID`)
    REFERENCES `COOKBOOK`.`USER` (`USER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
